name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o dist/macker

    - name: Test
      run: go test

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macker
        path: dist/macker